package str

const (
	Ampersand       = "&"
	And             = "and"
	Or              = "or"
	At              = "@"
	Asterisk        = "*"
	Star            = Asterisk
	Backslash       = "\\"
	Colon           = ":"
	comma           = ","
	Dash            = "-"
	Dollar          = "$"
	Dot             = "."
	DotDot          = ".."
	Empty           = ""
	Equals          = "="
	False           = "false"
	Slash           = "/"
	Hash            = "#"
	Hat             = "^"
	LeftBrace       = "{"
	LeftBracket     = "("
	LeftChev        = "<"
	Newline         = "\n"
	No              = "no"
	Null            = "null"
	Off             = "off"
	On              = "on"
	Percent         = "%"
	Pipe            = "|"
	Plus            = "+"
	QuestionMark    = "?"
	ExclamationMark = "!"
	Quote           = "\""
	Return          = "\r"
	Tab             = "\t"
	RightBrace      = "}"
	RightBracket    = ")"
	RightChev       = ">"
	Semicolon       = ";"
	SingleQuote     = "'"
	Backtick        = "`"
	Space           = " "
	Tilda           = "~"
	LeftSqBracket   = "["
	RightSqBracket  = "]"
	True            = "true"
	Underscore      = "_"
	Yes             = "yes"
	In              = "in"
	Crlf            = "\r\n"
)
